### ISSUE TITLE
Request github repo discussions be enabled here.

### ISSUE THREAD

**Issue by jeremy-donson** [magma/openschema#2]
Enabling github [repo discussions](https://docs.github.com/en/discussions/quickstart) is a good idea.
This and several other repo settings need to be enabled.

Meanwhile, we can start to github [issues](https://github.com/magma/mma-android/issues).

_By using labels for github issues and templates for both issues and pr's,
lots of things get organized quickly in terms of task planning, task mgt and task tracking._

Distributed team dev workflows evolve from coordinating team services:
- github issues + github [actions ci](https://github.com/magma/mma-android/actions)
- zenhub or jira projects
- slack notifications

**Comment by lucasgonze** [comment]
Repo being archived.
